language: python
sudo: false

env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=pypy3

install:
  - travis_retry pip install tox
  - travis_retry tox --notest

script:
  - tox
